// A curated set of lucide-react icon names offered in the admin "Add/Edit
// branch" form. BranchIcon.jsx already knows how to render any of these
// (and falls back to Landmark for anything not in lucide-react).
export const BRANCH_ICON_OPTIONS = [
  "Landmark",
  "Trophy",
  "BookOpen",
  "FileCheck",
  "UserPlus",
  "Wallet",
  "Users",
  "Cpu",
  "Library",
  "FlaskConical",
  "LineChart",
  "Link",
  "HeartHandshake",
  "GraduationCap",
  "Building",
  "ShieldCheck",
  "Scale",
  "Megaphone",
  "Eye",
  "ClipboardCheck",
  "ShoppingCart",
  "Bus",
  "Stethoscope",
  "Music",
  "MonitorPlay",
  "Briefcase",
  "Contact",
  "MessageSquareWarning",
  "FileSearch",
  "FileSpreadsheet",
  "PencilRuler",
  "BadgeCheck",
  "Gavel",
];